-- =====================================================
-- DSA CHAT DATABASE SCHEMA
-- PostgreSQL
-- =====================================================


-- =====================================================
-- DSA USER
-- =====================================================

CREATE TABLE IF NOT EXISTS public.dsa_user (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creation_date DATE NULL,
    description VARCHAR(255) NULL,
    email VARCHAR(255) NULL,
    firstname VARCHAR(255) NULL,
    interests VARCHAR[] NULL,
    last_updatetime DATE NULL,
    lastname VARCHAR(255) NULL,
    password VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,

    CONSTRAINT uk_dsa_user_username UNIQUE (username)
);


-- =====================================================
-- ROLE
-- =====================================================

CREATE TABLE IF NOT EXISTS public."role" (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role VARCHAR(255) NULL
);


-- =====================================================
-- USER ROLES
-- =====================================================

CREATE TABLE IF NOT EXISTS public.user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,

    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id)
        REFERENCES public.dsa_user(user_id),

    CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_id)
        REFERENCES public."role"(role_id),

    CONSTRAINT pk_user_roles
        PRIMARY KEY (user_id, role_id)
);


-- =====================================================
-- CHAT MESSAGE
-- =====================================================

CREATE TABLE IF NOT EXISTS public.chat_message (
    chat_message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(255) NULL,
    sender VARCHAR(255) NULL,
    sent_datetime TIMESTAMP(6) NULL,
    user_id BIGINT NULL,

    CONSTRAINT fk_chat_message_user
        FOREIGN KEY (user_id)
        REFERENCES public.dsa_user(user_id)
);


-- =====================================================
-- DSA EVENT
-- =====================================================

CREATE TABLE IF NOT EXISTS public.dsa_event (
    event_id UUID NOT NULL PRIMARY KEY,
    attendees BIGINT[] NULL,
    confirmed_attendees BIGINT[] NULL,
    create_time DATE NULL,
    declined_attendees BIGINT[] NULL,
    description VARCHAR(255) NULL,
    event_date DATE NULL,
    event_name VARCHAR(255) NULL,
    event_type VARCHAR(255) NULL,
    last_updatetime DATE NULL,
    tentative_attendees BIGINT[] NULL
);