// Code Generated by Sidekick is for learning and experimentation purposes only. filename: ChatWebSocketHandler.java
package com.dsa.chat.config;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;
import org.springframework.web.socket.CloseStatus;
import org.springframework.web.socket.TextMessage;
import org.springframework.web.socket.WebSocketSession;
import org.springframework.web.socket.handler.TextWebSocketHandler;

import java.io.IOException;
import java.net.URI;
import java.security.Key;
import java.util.Base64;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;

@Component
public class ChatWebSocketHandler extends TextWebSocketHandler {

    private static final Logger LOGGER =
            LoggerFactory.getLogger(ChatWebSocketHandler.class);

    private static final String SECRET_KEY =
            "POOIRBCVIAUJERGKLBVSDLBVAKWIEWOIEOHGJKLBVLSBVLSADOWOIGHKLHGKLSDHJFKLSDFI";

    private final Set<WebSocketSession> sessions =
            ConcurrentHashMap.newKeySet();

    @Override
    public void afterConnectionEstablished(WebSocketSession session)
            throws IOException {

        String token = extractTokenFromUri(session);

        if (token == null) {
            closeSession(session);
            return;
        }

        String username = extractUsernameFromToken(token);

        if (username == null || username.isBlank()) {
            closeSession(session);
            return;
        }

        session.getAttributes().put("username", username);
        sessions.add(session);

        LOGGER.info("User connected: {}", username);
    }

    @Override
    protected void handleTextMessage(
            WebSocketSession session,
            TextMessage message) throws IOException {

        String username =
                (String) session.getAttributes().get("username");

        if (username == null) {
            closeSession(session);
            return;
        }

        String chatMessage =
                "[" + username + "]: " + message.getPayload();

        broadcastMessage(chatMessage);
    }

    @Override
    public void afterConnectionClosed(
            WebSocketSession session,
            CloseStatus status) {

        sessions.remove(session);
        LOGGER.info("User disconnected");
    }

    private void broadcastMessage(String message) {
        for (WebSocketSession client : sessions) {
            if (!client.isOpen()) {
                sessions.remove(client);
                continue;
            }

            try {
                synchronized (client) {
                    if (client.isOpen()) {
                        client.sendMessage(new TextMessage(message));
                    }
                }
            } catch (IOException exception) {
                LOGGER.warn(
                        "Could not send message to session {}",
                        client.getId(),
                        exception
                );
            }
        }
    }

    private String extractTokenFromUri(WebSocketSession session) {
        URI uri = session.getUri();

        if (uri == null || uri.getQuery() == null) {
            return null;
        }

        for (String parameter : uri.getQuery().split("&")) {
            String[] parts = parameter.split("=", 2);

            if (parts.length == 2 && parts[0].equals("token")) {
                return parts[1];
            }
        }

        return null;
    }

    private String extractUsernameFromToken(String token) {
        try {
            Claims claims = Jwts.parserBuilder()
                    .setSigningKey(getSigningKey())
                    .build()
                    .parseClaimsJws(token)
                    .getBody();

            return claims.getSubject();
        } catch (Exception exception) {
            LOGGER.warn("JWT validation failed");
            return null;
        }
    }

    private Key getSigningKey() {
        byte[] keyBytes = Base64.getDecoder().decode(SECRET_KEY);
        return Keys.hmacShaKeyFor(keyBytes);
    }

    private void closeSession(WebSocketSession session) {
        try {
            if (session.isOpen()) {
                session.close();
            }
        } catch (IOException exception) {
            LOGGER.warn("Could not close WebSocket session", exception);
        }
    }
}
